[landing]
[landing.edito]
title="""Edito"""
content="""<div align="justify">
<strong><H3>"The future is not something we wait for, it’s something we build together.">/H3></strong>
<br>

After a 2024 filled with emotions, we are proud to have been selected to represent France for three consecutive years, from 2025 to 2027, at the Junior Olympics of the FIRST Global Challenge, starting with the FGC from October 29 to November 1, 2025, in Panama City.
<br><br>

We have launched a campaign to find sponsors, and your help in bringing in new partners would be greatly appreciated. Our robotics workshop focuses on the practice of STEM (Science, Technology, Engineering, and Mathematics), using real-world problems and interdisciplinary approaches. Today, it’s no longer enough to simply know, it’s essential to know how to act, meaning to be capable of :
<ul>
<li>solving complex problems,</li>
<li>analyzing data,</li>
<li>understanding technical systems,</li>
<li>collaborating with others.</li>
</ul>
<br>

Designing a robot to meet the requirements of a competition helps develop these skills, combining physics to understand :
<ul>
<li>movements,</li>
<li>mathematics for calculations and algorithms,</li>
<li>computer science for programming,</li>
<li>design for creating efficient robots,</li>
<li>communication for facilitating collaboration.</li>
</ul>
<br>

Children are naturally curious, and by exposing them early to STEM in a fun and practical way, we spark a lasting passion for science and technology. We Robot’s mission is to transform these curious young minds into tomorrow’s innovators.
<br><br>

We are deeply committed to the role of girls in science, diversity, and inclusion. In our club, girls are just as numerous as boys and are preparing to take their place in the world of engineering. Everyone is welcome, regardless of visible or hidden individual differences, and both the young participants and their parents develop a team spirit and a competitive mindset that allows everyone to thrive.
</div>
"""