baseURL = '/'
languageCode = 'fr'
defaultContentLanguage = 'fr'
defaultContentLanguageInSubdir = false
title = "We Robot"

summaryLength = 50

# THIS IS UNACCEPTALBE, I REALLY THOUGH THIS WAS THE DEFAULT IN HUGO!!
assetDir = "assets"


[languages]
[languages.fr]
languageCode='fr'
languageName="Français"
[languages.fr.params]
nextlang="en"
[languages.en]
languageCode='en'
languageName="English"
[languages.en.params]
nextlang="fr"
keywords = ["Gaillon", "Robotic", "We Robot", "France", "Association", "Local"]
slogan = "Robotic, together"
footer_description = """
Created in 2017, local association of robotic for youth, based in Gaillon, France. We participate to international and national competitions, winner of First Global Contest in Washington DC in 2017 and of World Adolescent Robotic Contest in Guyiang, China in 2018.
"""
[[languages.en.params.errors]]
id="unknown"
title="This is a error"
description= "Very sorry for that"

[[languages.en.params.errors]]
id="404"
title="Are you lost?"
description= "This page doesn't exist"

[sitemap]
changefreq = 'weekly'

[params]
error404message = "Page non trouvée"
dateFmt = "02.01.2006 15:04"
slogan = "La Robotique, ensemble"
favicon = "/images/logo.png"
footer_description = """
Créée en 2017, association locale de robotique pour les jeunes, basée à Gaillon en France. Nous participons à des concours nationaux ou internationaux, gagnant d'un prix au First Global Contest à Washington DC en 2017 et du World Adolescent Robotic Contest à Guyiang, Chine en 2018
"""
[[params.errors]]
id="unknown"
title="Erreur inconnue"
description= "C'est dommage, on ne saura jamais la cause de l'erreur..."
[[params.errors]]
id="404"
title="Vous vous êtes perdu ?"
description= "Cette page n'existe pas ou plus"

[params.landing]
title = "Construire, tester,apprendre, déployer"

  [params.landing.edito]
  title = "Edito"
  content = "<p>Une fois n'est pas coutume l'édito se met à jour en avril. Il y a une raison à cela : We Robot est de nouveau sélectionné pour représenter la France au <a href='https://first.global/fgc/'>FIRST Global Challenge 2024</a>  qui se tiendra à Athènes du 26 au 29 septembre 2024. C'est une fois de plus une occasion extraordinaire pour nos jeunes et nous espérons trouver le soutien financier nécessaire pour y participer.</p><p> L'adhésion gratuite pour les lycéen.nes qui seraient intéressé.es par la communication reste gratuite et nous avons bon espoir de former une équipe de communication de choc</p><p> Vous pouvez désormais nous trouver <a href='https://www.openstreetmap.org/node/7510411804'>avenue du Printemps de Prague</a> à Gaillon dans la résidence autonomie</p><p>Vous pouvez nous contacter par l'intermédiaire de <a href='https://werobot.fr/contact-us'>notre formulaire</a> et pour adhérer, cela se fait directement <a href='https://www.helloasso.com/associations/we-robot/adhesions/we-robot-2023-24'>en ligne ici</a>.</p>"

  [params.landing.mission]
  title = "Notre objectif"
  content = "Notre but principal est l'éducation ludique des jeunes dans le domaines des sciences et techniques.<br> Nous faisons participer, à des concours nationaux et internationaux de robotique, une équipe de jeunes motivés et passionnés.<br> Parallèlement, nous proposons une initiation à la robotique pour les enfants de 8 à 12 ans."
  action = "Voir plus..."

  [params.landing.support]
  title = "Soutenez nous"
  content = "La robotique est une activité onéreuse. Elle nécessite beaucoup de matériel (moteurs, capteurs, structures mécaniques, cartes électroniques, instruments de mesure, outils, visserie, ordinateur ...).<br>De plus les déplacements, particulièrement à l'international, ne sont pas à la portée de tous. <br> C'est pourquoi nous sommes toujours à la recherche de partenaires et de soutien financier."
  action = "Donner"


[params.defaultImage] 
local = true
src = "cover/cover.jpg"

[taxonomies]
imtag = 'imtags'

[menus]

[[menus.footer_left]]
name="Accueil"
url="/"

[[menus.footer_left]]
name="Blog"
url="/blog"

[[menus.footer_left]]
name="Photos"
url="/photos"

[[menus.footer_left]]
name="Donner"
url="/donate"

[[menus.footer_right]]
name="À Propos"
url="/about"

[[menus.footer_right]]
name="Où sommes nous"
url="/about#place"

[[menus.footer_right]]
name="Nous contacter"
url="/contact"

[[menus.footer_right]]
name="Mentions Légales"
url="/legals"

# theme = "custom"

# [markup]
#   [markup.goldmark]
#     [markup.goldmark.renderer]
#       unsafe = true

