baseURL = '/'
languageCode = 'fr'
defaultContentLanguage = 'fr'
defaultContentLanguageInSubdir = false
title = "We Robot"

summaryLength = 50

# THIS IS UNACCEPTALBE, I REALLY THOUGH THIS WAS THE DEFAULT IN HUGO!!
assetDir = "assets"


[languages]
[languages.fr]
languageCode='fr'
languageName="Français"
[languages.fr.params]
nextlang="en"
[languages.en]
languageCode='en'
languageName="English"
[languages.en.params]
nextlang="fr"
partner_per_compet="Our partners per tournament"
keywords = ["Gaillon", "Robotic", "We Robot", "France", "Association", "Local"]
slogan = "Robotic, together"
description = """
Created in 2017, local association of robotic for youth, based in Gaillon, France. We participate to international and national competitions, winner of First Global Contest in Washington DC in 2017 and of World Adolescent Robotic Contest in Guyiang, China in 2018.
"""
home = "Home"
previous = "Previous"
next = "Next"
about = "About"
place = "Where you can find us"
donate = "Donate"
loading = "Loading..."
more = "See more..."
page-not-supported = "We are sorry this page is not supported in your language yet."
[languages.en.params.landing]
title = "Build, Test, Learn, Deploy"

  [languages.en.params.landing.edito]
  title = "Edito"
  content = "The 2022-2023 season has once again been a great success for the Saturday morning digital workshop. Six teenagers have been very dedicated, and we have shared wonderful moments. The intervention at the Jardins de bas neighborhood house unfolded in a mixed manner due to numerous interruptions. In fact, it has been suspended this year, and we are waiting for the stabilization of its opening and planning to modify the intervention format. We prepared for the Junior Robotics French Cup, but the regional competition was canceled at the last minute, so we couldn't compete against others. <p> For this 2023-2024 school year, we are resuming with more or less the same ingredients: <ul><li>The Saturday digital workshop</li><li>Robotics competitions: <li>The <a href='https://first.global/fgc/'>FIRST Global Challenge</a> in Singapore in early October 2023</li><li>The <a href='https://robotiquefirstfrance.org/le-defi-robotique-2024/'>FIRST Tech Challenge</a> in Lyon in early April 2024</li></li><li>Continuing free membership for high school students interested in communication</li></ul> Furthermore, starting December 2, 2023, we are changing locations and you can find us <a href='https://www.openstreetmap.org/node/7510411804'>on Avenue du Printemps de Prague</a> in Gaillon.</p><p>You can contact us via <a href='https://werobot.fr/contact-us'>our form</a> and to join, you can do it directly <a href='https://www.helloasso.com/associations/we-robot/adhesions/we-robot-2023-24'>online here</a>.</p>"

  [languages.en.params.landing.mission]
  title = "Our goal"
  content = "Our main purpose is the playful education of teenagers in the fields of STEAM.<br>We have teams of motivated students participate in national and internation robotic competitions.<br>At the same time, we propose an initiation into robotics for children from 8 to 12 years old."
  action = "See more..."

  [languages.en.params.landing.support]
  title = "Support us"
  content = "Robotics is an expensive activity. It requires a lot of hardware (engines, sensors, mechanical elements, electronic boards, tools, nuts and bolts, computer ...).<br>Moreover, travel, especially internationally, is not within everyone's reach.<br>That's why we are always looking for partners and financial support."
  action = "Donate"


  [languages.en.params.blog]
  title = "Blog"
  description = "The Blog is THE place to find all the news and story from the team."

  [languages.en.params.legals]
  title = "Legals term"
  description = "See here the legals term of the website werobot.fr"

  [languages.en.params.articles]
  title = "Articles"
  all = "All articles"
  last = "Our last articles"
  empty = "No articles"

    [languages.en.params.articles.sort-by-dates]
    title = "Sort by dates"
    posts = "post(s)"
    close = "Close"

    [languages.en.params.articles.sort-by-years]
    title = "Sort by years"
    posts = "articles(s)"
    close = "Close"

  [languages.en.params.photos]
  title = "Photos"
  description = "Last pictures from the instragram account of the We Robot team."
  all = "All photos"
  last = "Our last photos"
  empty = "No photos"

  [languages.en.params.contact-us]
  title = "Contact us"
  description = "There are many way to contact the We Robot team, one of which is to use the form provided on this page."

    [languages.en.params.contact-us.president]
    title = "By contacting the president"

    [languages.en.params.contact-us.form]
    title = "By using the form"
    description = "If you have any questions or proposal, please contact us through the form below."
    field_required = "This field is required"
    recaptcha_required = "The recaptcha is required"
    invalid_email = "This email is invalid"
    not-enough-length = "You must be more precise..."
    submit = "Submit"
    loading = "Loading..."
    success = "Your message has been sent!"
    name = "Your name"
    name_placeholder = "John Doe"
    email = "Your email"
    email_placeholder = "john.doe@example.com"
    subject = "Subject"
    subject_placeholder = "Ubi est magnum nixus?"
    content = "Your message"
    content_placeholder = "Mineralis de fortis abaculus, imperium glos est fidelis gemna, cesaris."

  [languages.en.params.partners]
  title="Our partners"
  support-us = "They support us"

[[languages.en.params.errors]]
id="unknown"
title="This is a error"
description= "Very sorry for that"

[[languages.en.params.errors]]
id="404"
title="Are you lost?"
description= "This page doesn't exist"

[sitemap]
changefreq = 'weekly'

[params]
partner_per_compet="Nos partenaires par compétition"
mainSections= "blog"
error404message = "Page non trouvée"
dateFmt = "02.01.2006 15:04"
slogan = "La Robotique, ensemble"
favicon = "/images/logo.png"
description = """
Créée en 2017, association locale de robotique pour les jeunes, basée à Gaillon en France. Nous participons à des concours nationaux ou internationaux, gagnant d'un prix au First Global Contest à Washington DC en 2017 et du World Adolescent Robotic Contest à Guyiang, Chine en 2018
"""
home = "Accueil"
previous = "Précédent"
next = "Suivant"
about = "A propos"
place = "Où nous trouver"
donate = "Donner"
more = "Voir plus..."
loading = "Chargement..."
page-not-supported = "Cette page n'est pas disponible dans votre langue actuellement."


[[params.social]]
id="facebook"
weight=1
title="Facebook"
url="https://facebook.com/werobot"

[[params.social]]
id="instagram"
weight=2
title="Instagram"
url="https://instagram.com/werobot"

[[params.social]]
id="x"
weight=3
title="X"
url="https://x.com/werobot_fr"

#[[params.social]]
#id="youtube"
#weight=4
#title="Youtube"
#url="https://facebook.com/werobot"

[[params.social]]
id="github"
weight=5
title="GitHub"
url="https://github.com/werobot-france"

[[params.errors]]
id="unknown"
title="Erreur inconnue"
description= "C'est dommage, on ne saura jamais la cause de l'erreur..."
[[params.errors]]
id="404"
title="Vous vous êtes perdu ?"
description= "Cette page n'existe pas ou plus"

[params.landing]
title = "Construire, Tester, Apprendre, Déployer"

  [params.landing.edito]
  title = "Edito"
  content = "<p>Une fois n'est pas coutume l'édito se met à jour en avril. Il y a une raison à cela : We Robot est de nouveau sélectionné pour représenter la France au <a href='https://first.global/fgc/'>FIRST Global Challenge 2024</a>  qui se tiendra à Athènes du 26 au 29 septembre 2024. C'est une fois de plus une occasion extraordinaire pour nos jeunes et nous espérons trouver le soutien financier nécessaire pour y participer.</p><p> L'adhésion gratuite pour les lycéen.nes qui seraient intéressé.es par la communication reste gratuite et nous avons bon espoir de former une équipe de communication de choc</p><p> Vous pouvez désormais nous trouver <a href='https://www.openstreetmap.org/node/7510411804'>avenue du Printemps de Prague</a> à Gaillon dans la résidence autonomie</p><p>Vous pouvez nous contacter par l'intermédiaire de <a href='https://werobot.fr/contact-us'>notre formulaire</a> et pour adhérer, cela se fait directement <a href='https://www.helloasso.com/associations/we-robot/adhesions/we-robot-2023-24'>en ligne ici</a>.</p>"

  [params.landing.mission]
  title = "Notre objectif"
  content = "Notre but principal est l'éducation ludique des jeunes dans le domaines des sciences et techniques.<br> Nous faisons participer, à des concours nationaux et internationaux de robotique, une équipe de jeunes motivés et passionnés.<br> Parallèlement, nous proposons une initiation à la robotique pour les enfants de 8 à 12 ans."
  action = "Voir plus..."

  [params.landing.support]
  title = "Soutenez nous"
  content = "La robotique est une activité onéreuse. Elle nécessite beaucoup de matériel (moteurs, capteurs, structures mécaniques, cartes électroniques, instruments de mesure, outils, visserie, ordinateur ...).<br>De plus les déplacements, particulièrement à l'international, ne sont pas à la portée de tous. <br> C'est pourquoi nous sommes toujours à la recherche de partenaires et de soutien financier."
  action = "Donner"


[params.defaultImage] 
local = true
src = "cover/cover.png"



  [params.blog]
  title = "Blog"
  description = "Le Blog de We Robot, c'est comme la vie, il y a des haut et des bas."

  [params.legals]
  title = "Mentions légales"
  description = "Retrouvez ici les mentions légales du site werobot.fr"

  [params.articles]
  title = "Articles"
  all = "Tout les articles"
  last = "Nos derniers articles"
  empty = "Aucun articles disponibles"

    [params.articles.sort-by-dates]
    title = "Trier par dates"
    posts = "articles(s)"
    close = "Fermer"

    [params.articles.sort-by-years]
    title = "Trier par années"
    posts = "articles(s)"
    close = "Fermer"

  [params.photos]
  title = "Photos"
  description = "Vous trouverez ici les dernières photos instagram de l'équipe."
  all = "Toutes les photos"
  last = "Nos dernières photos"
  empty = "Pas de photos disponibles"

  [params.contact-us]
  title = "Contactez nous"
  description = "Il y a plusieurs façon de contacter l'équipe We Robot, l'une consiste à utiliser le formulaire founis sur cette page."

    [params.contact-us.president]
    title = "En contactant le président"

    [params.contact-us.form]
    title = "En utilisant le formulaire"
    description = "Pour toute question ou proposition, n'hésitez-pas à nous contacter à l'aide du formulaire ci-dessous."
    field_required = "Ce champs est requis"
    recaptcha_required = "Veuillez cocher le recaptcha"
    invalid_email = "Cet email est invalide"
    not-enough-length = "Vous devez être un peu plus précis..."
    submit = "Valider"
    loading = "Traitement de votre message..."
    success = "Votre message a bien été envoyé !"
    name = "Votre nom"
    name_placeholder = "Jean Dupont"
    email = "Votre email"
    email_placeholder = "jean.dupont@exemple.fr"
    subject = "Sujet"
    subject_placeholder = "Ubi est magnum nixus?"
    content = "Votre message"
    content_placeholder = "Mineralis de fortis abaculus, imperium glos est fidelis gemna, cesaris."

  [params.partners]
  title="Nos partenaires"
  support-us = "Ils nous soutiennent"












[taxonomies]
imtag = 'imtags'
tag="tags"
category="categories"


[menus]

[[menus.main]]
weight=1
url="/"
identifier="home"
title="Accueil"

[[menus.main]]
weight=2
identifier="blog"
url="/blog"
title="Blog"

[[menus.main]]
weight=3
identifier="about"
url="/about"
title="A Propos"

[[menus.main]]
weight=4
identifier="partners"
url="/partners"
title="Nos partenaires"

[[menus.main]]
weight=4
identifier="contact-us"
url="/contact"
title="Contact"

[[menus.main]]
weight=5
identifier="donate"
url="https://www.helloasso.com/associations/we-robot/formulaires/1"
title="Donner"
[menus.main.params]
customClass="link-primary"


[[menus.footer_left]]
weight=1
identifier="home"
title="Accueil"
url="/"

[[menus.footer_left]]
weight=2
identifier="blog"
title="Blog"
url="/blog"

[[menus.footer_left]]
weight=3
identifier="photos"
title="Photos"
url="/photos"

[[menus.footer_left]]
weight=4
identifier="donate"
title="Donner"
url="https://www.helloasso.com/associations/we-robot/formulaires/1"

[[menus.footer_right]]
weight=1
identifier="about"
title="À Propos"
url="/about"

[[menus.footer_right]]
weight=2
identifier="where"
title="Où sommes nous"
url="/about#place"

[[menus.footer_right]]
weight=3
identifier="contact-us"
title="Nous contacter"
url="/contact"

[[menus.footer_right]]
weight=4
identifier="legals"
title="Mentions Légales"
url="/legals"





[permalinks]
    blog = "/blog/:year/:slugorfilename/"

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

